parsemail: Use logging instead of prints
This is more useful for helpful dialog messages. Without this it is
necessary to add prints to figure out why patches aren't parsed.

v2: Make the patch apply on fdo's patchwork (Damien)
v3: Remove 'bin/' from the commit message (Damien)
v4: Make the thing actually work (Damien).
    Using the verbosity argument was throwing an exception:

    File "patchwork/patchwork/bin/parsemail.py", line 816, in main
      logging.basicConfig(level=args['verbosity'])
    File "/usr/lib64/python2.7/logging/__init__.py", line 1556, in basicConfig
      root.setLevel(level)
    File "/usr/lib64/python2.7/logging/__init__.py", line 1141, in setLevel
      self.level = _checkLevel(level)
    File "/usr/lib64/python2.7/logging/__init__.py", line 188, in _checkLevel
      raise ValueError("Unknown level: %r" % level)
    ValueError: Unknown level: 'debug'

v5: Change log messages to use 'mail' instead of 'patch' as we are
    parsing all mails, not just patches. (Damien)
    Change the argument help string from 'debug level' to 'logging
    level'. Can't say that 'warning' is a 'debug level'. (Damien)

Signed-off-by: Stephen Finucane <stephen.finucane@intel.com>
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>