tox: Use a range of ports for live servers in case of concurrent runs
 From:
 https://docs.djangoproject.com/en/1.8/topics/testing/tools/#liveservertestcase

In the case where the tests are run by multiple processes in parallel (for
example, in the context of several simultaneous continuous integration builds),
the processes will compete for the same address, and therefore your tests might
randomly fail with an “Address already in use” error.

And indeed it was hapening in my setup:

Traceback (most recent call last):
  File
  ".../python2.7/site-packages/django/test/testcases.py",
  line 1193, in setUpClass
      raise cls.server_thread.error
      error: [Errno 98] Address already in use

Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
Acked-by: Stephen Finucane <stephen.finucane@intel.com>